---
title: "Lab 11"
author: "Jahiya Clark"
date: "12/15/2021"
output: html_document
---

```{r setup, include=FALSE}
require(here)

alpha = 0.05
n_sims = 100
p_vals = numeric(n_sims)

bird <- data.frame(read.csv(here("data", "bird.sub.csv")))
hab <- data.frame(read.csv(here("data", "hab.sub.csv")))
birdhab <- merge(bird, hab)
fit_1 = lm(BRCR ~ ls, data = birdhab)

linear_simulator = function(x, y_int, slope, st_dev)
{
  y_int + (x * slope) + rnorm(length(x),  sd = st_dev)
}

fit_1_coefs = coefficients(fit_1)
str(fit_1_coefs)

fit_1_summary = summary(fit_1)
str(fit_1_summary)


linear_sim_fit = function(x, slope, y_int, st_dev)
{
  y_sim = linear_simulator(
    x = x,
    y_int = y_int,
    slope = slope,
    st_dev = st_dev
  )
  fit_sim = lm(y_sim ~ x)
  return(fit_sim)
}
```

```{r}
# What was the observed standard deviation?

sd_obs = fit_1_summary$sigma
int_obs = fit_1_summary$coefficients[1,1]
slope_obs = fit_1_summary$coefficients[2,1]; slope_obs


```
```{r}
# specify the number of different standard deviation values to simulate:
n_sds = 20
pop_sds = seq(from = 0.01, to = 1.5, length.out = n_sds)

pop_sd_power = numeric(length(n_sds))

for(j in 1:length(pop_sds))
{
  pop_sd_j = pop_sds[j]
  for(i in 1:n_sims)
  {
    fit_sim = linear_sim_fit(
      x = birdhab$ls,
      y_int = int_obs,
      slope = slope_obs,
      st_dev = pop_sds[j])
    p_vals[i] = summary(fit_sim)$coefficients[2, 'Pr(>|t|)']
  }
  pop_sd_power[j] = sum(p_vals < alpha) / n_sims
}

sim_output_dispersion = 
  data.frame(
  sd = pop_sds,
  power = pop_sd_power)

# You should save your simulation results so you don't have to run it every time.
save(
  sim_output_dispersion, 
  file = here("data", "lab_ll_dat_dispersion_sim.RData"))

# Line plot of standard deviation (x-axis) and statistical power (y-axis)

plot(
  power ~ sd, data = sim_output_dispersion,
  xlab = "Standard Deviation", 
  ylab = "Stastical Power",
  type = "line")

# Add a dotted vertical red line at the observed population standard deviation value.
abline(v = sd_obs, lty = 2, col = '#F95B5B')

```


```{r}
alpha = 0.05

# Start with a small number
n_sims = 100
p_vals = numeric(n_sims)

# What was the observed standard deviation?
sd_obs

# specify the number of different standard deviation values to simulate:
# Start with a small number
n_sds = 20
pop_sds = seq(from = 0.05, to = 2.0, length.out = n_sds)

pop_sd_power = numeric(length(n_sds))

sample_sizes = seq(5, 100)

sim_output_3 = matrix(nrow = length(pop_sds), ncol = length(sample_sizes))

for(k in 1:length(pop_sds))
{
  pop_sd_k = pop_sds[k]
  
  for(j in 1:length(sample_sizes))
  {
    x_vals = seq(0, 100, length.out = sample_sizes[j])
    
    for(i in 1:n_sims)
    {
      fit_sim = linear_sim_fit(
        x = x_vals,
        y_int = int_obs,
        slope = slope_obs,
        st_dev = pop_sd_k
      )
      p_vals[i] = summary(fit_sim)$coefficients[2, 'Pr(>|t|)']
    }
    
    sim_output_3[k, j] = sum(p_vals < alpha) / n_sims
  }
  print(paste0("Testing standard deviation ", k, " of ", n_sds))
}

image(sim_output_3)

sim_3_dat = 
  list(
    power       = sim_output_3,
    sample_size = sample_sizes,
    pop_sd      = pop_sds)


# You should save your simulation results so you don't have to run it every time.
save(
  sim_3_dat, 
  file = here::here("data", "lab_ll_sim_output_dispersion_n_100.RData"))

```

## Questioin 2 

The statistical power decreases because more variability is 
